name: Demo Workflow

on:      #trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest    #one vm
      steps:
    #step1
        - name: checkout the repo
          uses: actions/checkout@v2
    #step2
        - name: setup python
          uses: actions/setup-python@v2
    #step3
        - name: install pytest #as we dont have a specific req.txt file in folder from where it can get the pytest
          run: pip install pytest
    #step4
        - name: run test
          run: pytest  